name: khosikasi_game
description: A new Flutter project with an African theme to inspire entrepreneurship.

publish_to: 'none' # Prevent accidental publishing.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0' # Update if your Dart version is different.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.1.1
  flutter_svg: ^2.0.7
  animated_text_kit: ^4.2.2
  page_view_indicators: ^2.0.0
  flame: ^1.22.0
  flame_audio: ^2.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/sound/intro.mp3
    - assets/audio/sound/menu.mp3
  # assets:
  #   - assets/images/
  #   - assets/icons/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
